from django.urls import path

from . import feedback_views, reading_views, views


urlpatterns = [
    path(
        "",
        views.dashboard,
        name="dashboard",
    ),
    path(
        "feedback/submit/",
        feedback_views.submit_beta_feedback,
        name="submit_beta_feedback",
    ),
    path(
        "onboarding/",
        views.onboarding,
        name="onboarding",
    ),
    path(
        "goals/",
        views.goals,
        name="goals",
    ),
    path(
        "review/",
        views.review,
        name="review",
    ),
    path(
        "subjects/<int:subject_index>/",
        views.subject_detail,
        name="subject_detail",
    ),
    path(
        "subjects/<int:subject_index>/definition/",
        views.definition,
        name="definition",
    ),
    path(
        "review/definitions/",
        views.review_definitions,
        name="review_definitions",
    ),
    path(
        "review/definitions/<int:definition_id>/read/",
        views.read_definition,
        name="read_definition",
    ),
    path(
        "progress/",
        views.progress,
        name="progress",
    ),
    path(
        "review/formulas/",
        views.review_formulas,
        name="review_formulas",
    ),
    path(
        "review/lists/",
        views.review_lists,
        name="review_lists",
    ),
    path(
        "review/steps/",
        views.review_steps,
        name="review_steps",
    ),
    path(
        "review/notes/",
        views.review_notes,
        name="review_notes",
    ),
    path(
        "review/comparisons/",
        views.review_comparisons,
        name="review_comparisons",
    ),
    path(
        "review/<str:kind>/<int:item_id>/read/",
        reading_views.read_review_item,
        name="read_review_item",
    ),
]
