# Generated by Django 4.2.30 on 2026-08-24 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_enabled', models.BooleanField(default=False)),
                ('monday_time', models.CharField(blank=True, default='', max_length=5)),
                ('tuesday_enabled', models.BooleanField(default=False)),
                ('tuesday_time', models.CharField(blank=True, default='', max_length=5)),
                ('wednesday_enabled', models.BooleanField(default=False)),
                ('wednesday_time', models.CharField(blank=True, default='', max_length=5)),
                ('thursday_enabled', models.BooleanField(default=False)),
                ('thursday_time', models.CharField(blank=True, default='', max_length=5)),
                ('friday_enabled', models.BooleanField(default=False)),
                ('friday_time', models.CharField(blank=True, default='', max_length=5)),
                ('saturday_enabled', models.BooleanField(default=False)),
                ('saturday_time', models.CharField(blank=True, default='', max_length=5)),
                ('sunday_enabled', models.BooleanField(default=False)),
                ('sunday_time', models.CharField(blank=True, default='', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_availability', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
