# Generated by Django 4.2.30 on 2026-08-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_subjecttextbook_subjectrevisionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttextbook',
            name='last_summary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjecttextbook',
            name='pages_summarized',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
