# Generated by Django 5.2.17 on 2026-09-29 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_beta_lifetime_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('active', 'Active'), ('non_renewing', 'Not renewing'), ('past_due', 'Payment failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=100)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
