# Generated by Django 5.2.17 on 2026-09-30 17:39

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_studymembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=accounts.models.new_study_payment_reference, editable=False, max_length=40, unique=True)),
                ('plan', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=4)),
                ('source', models.CharField(choices=[('checkout', 'Checkout'), ('renewal', 'Subscription renewal')], default='checkout', max_length=10)),
                ('expected_amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Awaiting payment'), ('succeeded', 'Verified successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('reversed', 'Reversed')], default='created', max_length=12)),
                ('paystack_transaction_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('expected_amount_cents__gt', 0)), name='study_payment_positive_amount'), models.UniqueConstraint(condition=models.Q(('paystack_transaction_id__isnull', False)), fields=('mode', 'paystack_transaction_id'), name='study_payment_unique_transaction_per_mode')],
            },
        ),
    ]
