# Generated by Django 4.2.30 on 2026-08-08 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.TextField(default='[]')),
                ('purpose', models.TextField(blank=True)),
                ('when_to_use', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(default='#2563EB', max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.subject')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('knowledge_type', models.CharField(choices=[('FORMULA', 'Formula'), ('DEFINITION', 'Definition'), ('BULLET_LIST', 'Bullet List')], max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=2)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_units', to='learning.topic')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='learning.formula')),
            ],
        ),
        migrations.AddField(
            model_name='formula',
            name='knowledge_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='learning.knowledgeunit'),
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('knowledge_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning.knowledgeunit')),
            ],
        ),
        migrations.CreateModel(
            name='BulletList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('knowledge_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning.knowledgeunit')),
            ],
        ),
        migrations.CreateModel(
            name='BulletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('bullet_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.bulletlist')),
            ],
        ),
    ]
