# Generated by Django 4.2.30 on 2026-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_studentknowledge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulavariable',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulavariable',
            name='incorrect_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
