# Generated by Django 4.2.30 on 2026-08-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_formulavariable_correct_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulavariable',
            name='correct_count',
        ),
        migrations.RemoveField(
            model_name='formulavariable',
            name='incorrect_count',
        ),
        migrations.CreateModel(
            name='FormulaElementPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=100)),
                ('element_type', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_performance', to='learning.formula')),
            ],
        ),
    ]
