# Generated by Django 4.2.30 on 2026-08-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_formulavariable_correct_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeunit',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_units', to='learning.subject'),
        ),
        migrations.AlterField(
            model_name='knowledgeunit',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_units', to='learning.topic'),
        ),
    ]
