# Generated by Django 4.2.30 on 2026-08-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_knowledgeunit_subject_alter_knowledgeunit_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgeunit',
            name='topic',
        ),
    ]
