# Generated by Django 4.2.30 on 2026-08-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_knowledgeunit_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bulletlist',
            name='book_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bulletlist',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
