# Generated by Django 4.2.30 on 2026-09-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_bulletitem_description_bulletlist_book_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='bulletlist',
            name='knowledge_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_list', to='learning.knowledgeunit'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='knowledge_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='definition', to='learning.knowledgeunit'),
        ),
        migrations.AlterField(
            model_name='knowledgeunit',
            name='knowledge_type',
            field=models.CharField(choices=[('FORMULA', 'Formula'), ('DEFINITION', 'Definition'), ('BULLET_LIST', 'Bullet List'), ('STEPS', 'Steps')], max_length=20),
        ),
        migrations.CreateModel(
            name='StepList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('book_name', models.CharField(blank=True, default='', max_length=255)),
                ('chapter', models.CharField(blank=True, default='', max_length=255)),
                ('knowledge_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_list', to='learning.knowledgeunit')),
            ],
        ),
        migrations.CreateModel(
            name='StepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=1)),
                ('step_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning.steplist')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
