# Generated by Django 4.2.30 on 2026-09-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_bulletitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='book_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='formula',
            name='chapter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
