# Generated by Django 4.2.30 on 2026-09-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_studied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
