# Generated by Django 4.2.30 on 2026-09-06 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_note_last_studied_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('book_name', models.CharField(blank=True, default='', max_length=255)),
                ('chapter', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='knowledgeunit',
            name='knowledge_type',
            field=models.CharField(choices=[('FORMULA', 'Formula'), ('DEFINITION', 'Definition'), ('BULLET_LIST', 'Bullet List'), ('STEPS', 'Steps'), ('COMPARISON', 'Comparison')], max_length=20),
        ),
        migrations.CreateModel(
            name='ComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='learning.comparison')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='learning.comparison')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='learning.comparisoncolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='learning.comparisonrow')),
            ],
        ),
        migrations.AddField(
            model_name='comparison',
            name='knowledge_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='learning.knowledgeunit'),
        ),
        migrations.AddConstraint(
            model_name='comparisonrow',
            constraint=models.UniqueConstraint(fields=('comparison', 'order'), name='unique_comparison_row_order'),
        ),
        migrations.AddConstraint(
            model_name='comparisoncolumn',
            constraint=models.UniqueConstraint(fields=('comparison', 'order'), name='unique_comparison_column_order'),
        ),
        migrations.AddConstraint(
            model_name='comparisoncell',
            constraint=models.UniqueConstraint(fields=('row', 'column'), name='unique_comparison_cell'),
        ),
    ]
