# Generated by Django 4.2.30 on 2026-09-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_comparison_alter_knowledgeunit_knowledge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonrow',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
